name: genz_dictionary
description: Gen Z Dictionary MVP - offline-first, neon visuals, shareable cards
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State / nav
  flutter_riverpod: ^2.5.1
  go_router: ^16.2.1

  # Utils
  http: ^1.2.2
  google_fonts: ^6.2.1
  intl: ^0.20.2

  # Share card
  screenshot: ^3.0.0
  share_plus: ^11.1.0

  # Animations (optional)
  lottie: ^3.1.2

  # Icons
  cupertino_icons: ^1.0.8
  confetti: ^0.8.0
  qr_flutter: ^4.1.0
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  cloud_firestore: ^6.0.1
  uuid: ^4.4.2
  shared_preferences: ^2.2.3
  firebase_messaging: ^15.0.4
  flutter_local_notifications: ^17.2.1
  timezone: ^0.9.2
  





dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/data/slang_local.json
    - assets/lottie/loading.json
